services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
  
  producer:
    build: ./producer
    ports:
      - 9000:9000
  
  consumer:
    build: ./consumer
